name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.26.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download

    - name: Build
      run: |
        go build ./...

    - name: Run tests
      run: |
        go test ./... -v

    - name: Run tests with coverage
      run: |
        go test ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: zients/go-trading-ace
